spring.application.name=clase-service
spring.datasource.url=jdbc:mysql://localhost:3310/clase_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

server.port=8084